### ISSUE TITLE
idians and EnchantEffect do not lose their level.

### ISSUE THREAD

**Issue by cmd-balboa** [beyond-aion/aion-server#16]
idians and EnchantEffect do not lose their level.

**Comment by neon-dev** [comment]
The charge value of Idians decreases in combat, so please elaborate. Specifying the reproduction steps from the issue template would also help us to understand your exact problem.

**Comment by cmd-balboa** [comment]
Even after many fights, the charge does not decrease. I've tried to die many times, but nothing changes.

**Comment by neon-dev** [comment]
There were no issues during testing. The Idian charge decreases normally with each hit and the Idian is removed once the charge value reaches zero. The `polishCharge` value also updates correctly in DB when logging out.

I'll have to close this unless you can provide reproduction steps and info how you identified your issues here.
