### ISSUE TITLE
On create player SQL error

### ISSUE THREAD

**Issue by podpol** [beyond-aion/aion-server#6]
### Description

![2024-07-12_014321](https://github.com/user-attachments/assets/29159545-3c1c-4d1a-98b9-72173119b510)
Just creating normal player.

### Reproduction steps

1.
2.
3.

**Comment by neon-dev** [comment]
Your database schema is not up to date.
See https://github.com/beyond-aion/aion-server/commit/fd39fec4f3cd55d8ecf36c1ffcf86d199d7c74de#diff-c3584e46d493aa087cd246422a3a7bc24ac690f8780577b6018bbda568ffa904
